config/routes.rb
Rails.application.routes.draw do
  root to:"sessions#new"
  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :task_labels, dependent: :destroy
  has_many :tasks, through: :task_labels
end

app/models/task.rb
class Task < ApplicationRecord
  extend Enumerize
  enumerize :status, in: { 未着手: 0, 着手中: 1, 完了: 2 }
  enumerize :priority, in: { 高: 2, 中: 1, 低: 0}

  belongs_to :user
  has_many :task_labels, dependent: :destroy
  has_many :labels, through: :task_labels

  validates :name, presence: true, length: {maximum: 50}
  validates :detail, presence: true, length: {maximum: 200}
  validates :deadline, presence: true

  scope :sort_by_crated_at, -> {order(created_at: :desc)}
  scope :sort_by_deadline, -> {order(deadline: :asc)}
  scope :sort_by_priority, -> {order(priority: :desc)}
  scope :search_by_name, -> (search){where(['name LIKE ?', "%#{search[:name]}%"]) if search[:name].present?}
  scope :search_by_status, -> (search){where(status: "#{search[:status]}") if search[:status].present?}
  scope :search_by_labels, -> (task_ids){where(id: task_ids)}

  def self.search(search)
    task_ids = TaskLabel.where(label_id: search[:label_ids]).pluck(:task_id)
    if task_ids.present?
      Task.search_by_name(search).search_by_status(search).search_by_labels(task_ids)
    else
      Task.search_by_name(search).search_by_status(search)
    end
  end
  
end

app/models/task_label.rb
class TaskLabel < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy

  before_update :protection_admin
  before_destroy :protection_admin

  has_secure_password
  validates :name,  presence: true
  validates :email, presence: true, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }
  before_validation { email.downcase! }

  scope :sort_by_id, -> {order(id: :asc)}

  private

  def  protection_admin
    admin_user = User.where(admin: true)
    if admin_user.length == 1  && self.admin == true
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_check
  before_action :set_user, only:[:show, :edit, :update, :destroy]

  USER_PER = 8
  TASK_PER = 5

  def index
    @users=User.sort_by_id.includes(:tasks).page(params[:page]).per(USER_PER)
  end

  def new
    @user = User.new
  end

  def show
    @tasks = @user.tasks.page(params[:page]).per(TASK_PER)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'ユーザーを作成しました'
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: 'ユーザーを編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: 'ユーザーを削除しました'
    else
      redirect_to admin_users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user= User.find(params[:id])
  end

  def admin_check
    if current_user
      unless current_user.admin == true
        raise Forbidden
      end
    else
      redirect_to new_session_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  class Forbidden < ActionController::ActionControllerError; end
  class IpAddressRejected < ActionController::ActionControllerError; end

  rescue_from Forbidden, with: :rescue403

  def rescue403(e)
    @exception = e
    render 'errors/403.html', status: 403, layout:  false
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'ログインしました'
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_id, only:[:show,:edit,:update,:destroy]
  before_action :login_check

  PER = 5

  def index
    if params[:sort_expired]
      @tasks = current_user.tasks.sort_by_deadline
    elsif params[:sort_priority]
      @tasks =current_user.tasks.sort_by_priority
    elsif params[:task]
      @tasks = current_user.tasks.search(params[:task] ).sort_by_crated_at
    else
      @tasks = current_user.tasks.sort_by_crated_at
    end

    @tasks = @tasks.page(params[:page]).per(PER)
  end

  def new
    @task = Task.new
  end

  def show
    @labels = @task.labels
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice: 'タスクを作成しました'
    else
      render 'new'
    end
  end

  def update
    if@task.update(task_params)
      redirect_to tasks_path, notice: 'タスクを編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: 'タスクを削除しました'
  end

  private

  def task_params
    params.require(:task).permit(:name, :detail, :deadline, :status, :priority, { label_ids: [] })
  end

  def set_id
    @task = Task.find(params[:id])
  end

  def login_check
    unless logged_in?
      redirect_to new_session_path, notice: 'ログインしてください'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if logged_in?
      redirect_to user_path(current_user.id)
    else
      @user=User.new
    end
  end

  def show
    if params[:id].to_i == current_user.id
      @user = User.find(params[:id])
    else
      redirect_to user_path(current_user.id)
    end
  end

 def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'ログインしました'
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="admin_form">
  <h1><%= "#{admin_title}" %></h1>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @user,url: url,  local: true) do |f| %>
    <div class="user_name">
      <p>
        <%= f.label :name %>
      </p>
      <p>
        <%= f.text_field :name %>
      </p>
    </div>

    <div class="user_email">
      <p>
        <%= f.label :email %>
      </p>
      <p>
        <%= f.email_field :email %>
      </p>
    </div>

    <div class="user_password">
      <p>
        <%= f.label :password %>
      </p>
      <p>
        <%= f.password_field :password %>
      </p>
    </div>

    <div class="user_password_confirmation">
      <p>
        <%= f.label :password_confirmation %>
      </p>
      <p>
        <%= f.password_field :password_confirmation %>
      </p>
    </div>

    <div class="admin">
      <p>
        <%= f.label :admin %>
      </p>
      <p>
        <%= f.check_box :admin, {} , true, false %>
      </p>
    </div>

    <%= f.submit "#{submit}", class: 'user_save' %>

  <% end %>

</div>

app/views/admin/users/edit.html.erb
<% admin_edit = 'ユーザー編集' %>
<% edit_url = admin_user_path %>
<% admin_user_edit = 'ユーザーを編集する' %>
<%= render 'admin/users/form', admin_title: admin_edit, url: edit_url, submit: admin_user_edit%>

app/views/admin/users/index.html.erb
<div class="users">
  <% @users.each do |user| %>
  <div class="user">
    <p>
      <%= user.id %>
    </p>
    <p>
      <%= link_to "#{user.name}", admin_user_path(user.id) %>
       タスク<%= user.tasks.length %>個
    </p>
  </div>
  <% end %>

  <div class="page_option">
    <%= paginate @users, id: 'page_option'%>
  </div>

  <%= link_to 'ユーザーを作成する', new_admin_user_path, class: 'admin_user_create' %>

</div>

app/views/admin/users/new.html.erb
<% admin_new = 'ユーザー登録' %>
<% new_url = admin_users_path %>
<% admin_user_new = 'ユーザーを作成する' %>

<%= render 'admin/users/form', admin_title: admin_new, url: new_url, submit: admin_user_new %>

app/views/admin/users/show.html.erb
<div class="admin_show">
  <div class="user_detail">
    <h3>ユーザー詳細</h3>

    <p><%= @user.name %></p>
    <p><%= @user.email %></p>

    <p>
      <%= link_to '編集', edit_admin_user_path(@user.id), class: 'btn btn-info' %>
      <%= link_to '削除', admin_user_path(@user.id), method: :delete, data: { confirm: '本当に削除しますか?' },class: 'btn btn-danger' %>
    </p>
  </div>

  <div class="tasks">
    <% @tasks.each do |task| %>
    <div class="task">
      <%= link_to "#{task.name} &ensp;(#{task.status})".html_safe, task, class: "task_link" %>
      <p>
        優先度 &nbsp; <%= task.priority %>
      </p>
      <%= l task.deadline %>
    </div>
    <% end %>
    <%= paginate @tasks %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manyou</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <header>
        <h1 id='title'>My ToDoList</h1>
        <% if logged_in? %>
          <%= link_to "ログアウト", session_path(current_user.id), method: :delete,  class: 'session_right' %>
          <%= link_to "マイページ", user_path(current_user.id) %>
        <% else %>
          <%= link_to "サインアップ", new_user_path, class: 'session_right' %>
          <%= link_to "ログイン", new_session_path %>
        <% end %>
      </header>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    <div class="row">
      <%= yield %>
    </div>
    <footer>
      <h3></h3>
    </footer>
  </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="form">
  <h1><%= "#{form_title}" %></h1>
  <%= form_with(model: @task, local: true) do |f| %>
  <% if @task.errors.any? %>
    <div id='error_explanation'>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="task_form">
      <div class='task_title'>
        <p>
          <%= f.label :name %>
        </p>
        <p>
          <%= f.text_field :name %>
        </p>
      </div>

      <div class='task_detail'>
        <p>
          <%= f.label :detail %>
        </p>
        <p>
          <%= f.text_area :detail %>
        </p>
      </div>

      <div class='task_deadline'>
        <p>
          <%= f.label :deadline %>
        </p>
        <p>
          <%= f.datetime_select :deadline %>
        </p>
      </div>

      <div class='task_status'>
        <p>
          <%= f.label :status %>
        </p>
        <p>
          <%= f.select :status ,Task.status.options  %>
        </p>
      </div>

      <div class="task_priority">
        <p>
          <%= f.label :priority %>
        </p>
        <p>
          <%= f.select :priority, Task.priority.options %>
        </p>
      </div>
    </div>

    <div class="task_labels_form">
      <div class="label_id">
        <p class="label_label">
          <%= f.label :ラベル %>
        </p>
        <p>
          <%= f.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
        </p>
      </div>
    </div>

    <p class="task_create">
      &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
      <%= f.submit "#{form_name}", id: 'task_save' %>
    </p>
  <% end %>

</div>

app/views/tasks/edit.html.erb
<% form_edit = 'タスク編集' %>
<%= render 'form', form_title: form_edit, form_name: form_edit %>

app/views/tasks/index.html.erb
<div class="task_index col-md-7">
  <h2>タスク一覧</h2>

  <div class="sort_links">
    <p>
      <%= link_to '終了期限でソートする', tasks_path(sort_expired: "true") %>
    </p>
    <p class="bottom_link">
      <%= link_to '優先度でソートする', tasks_path(sort_priority: "true") %>
    </p>
    <p class="reset">
      <%= link_to 'リセット', tasks_path %>
    </p>
  </div>

  <div class="tasks">
    <% @tasks.each do |task| %>
    <div class="task">
      <%= link_to "#{task.name} &ensp;(#{task.status})".html_safe, task, class: "task_link" %>
      <p>
        優先度 &nbsp; <%= task.priority %>
      </p>
      <%= l task.deadline %>
    </div>
    <% end %>
  </div>

  <%= link_to 'タスクを作成する', new_task_path %>

  <%= paginate @tasks %>
</div>

<div class="col-md-5">
  <div class="searchs">
    <h3>検索</h3>

    <%= form_with(model: Task.new, url: tasks_path, method: :get, local: true) do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :status %>
      <%= f.select :status, Task.status.options, include_blank: true, selected: '' %>
    </p>
    <p class="label_label">
      <%= f.label :ラベル %>
    </p>
    <p>
      <%= f.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
    </p>
      <%= f.submit '検索', id: 'search_button' %>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<% form_new = 'タスク作成' %>
<%= render 'form', form_title: form_new, form_name: form_new %>

app/views/tasks/show.html.erb
<div class="task_show">
  <div class="content">
    <h3>タスク詳細</h3>

    <p class="task_top">
      タスク名 &ensp; <%= @task.name %>&ensp;(<%= @task.status %>)
    </p>
    <p class="middle">
      優先度 &ensp; &ensp; <%= @task.priority %>
    </p>
    <p class="middle">
      終了期限&ensp; <%= l @task.deadline %>
    </p>
    <p class="task_detail task_last">
      <%= @task.detail %>
    </p>

    <div class="task_option">
      <%= link_to '編集', edit_task_path(@task), class: 'btn btn-info' %>
      <%= link_to '削除', @task, method: :delete, data: { confirm: '本当に削除しますか?' },  class: 'btn btn-danger' %>
    </div>
    <br>

    <% @labels.each do |label|%>
    <p class='label'>
      <%= label.name %><a href="#"> </a>
    </p>
    <% end %>

    <p>
      <%= link_to 'タスク一覧へ', tasks_path %>
    </p>
  </div>
</div>

app/views/users/new.html.erb
<div class="user_new">
  <h1>サインアップ</h1>

  <% if @user.errors.any? %>
    <div class="error_explanation">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @user, local: true) do |f| %>
  <div class="user_name">
    <p>
      <%= f.label :name %>
    </p>
    <p>
      <%= f.text_field :name %>
    </p>
  </div>

  <div class="user_email">
    <p>
      <%= f.label :email %>
    </p>
    <p>
      <%= f.email_field :email %>
    </p>
  </div>

  <div class="user_password">
    <p>
      <%= f.label :password %>
    </p>
    <p>
      <%= f.password_field :password %>
    </p>
  </div>

  <div class="user_password_confirmation">
    <p>
      <%= f.label :password_confirmation %>
    </p>
    <p>
      <%= f.password_field :password_confirmation %>
    </p>
  </div>

  <p>
    <%= f.submit "ユーザー登録", class: 'user_save' %>
  </p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user_show">
  <h1><%= @user.name %>のページ</h1>

  <p>メールアドレス: <%= @user.email %></p>

  <%= link_to 'タスク一覧へ', tasks_path %>

</div>